name: New project
description: Fill this form to add your project/library to the website.
title: "[New][Project]: "
labels: ["new", "project"]

body:
  - type: markdown
    attributes:
      value: |
        Tell us about your project.

  - type: input
    id: author
    attributes:
      label: Author fullname
      placeholder: ex. John Doe
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Author contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    id: contact-handler
    attributes:
      label: Author handler
      placeholder: https://github.com/user
    validations:
      required: false

  - type: input
    id: project
    attributes:
      label: Project title
      description: Add a title for your project
      placeholder: ex. react-popup
    validations:
      required: false

  - type: input
    id: project-url
    attributes:
      label: Project URL
      description: Add a url for your project (repository or website)
      placeholder: ex. https://github.com/user/project
    validations:
      required: true

  - type: dropdown
    id: is-oss
    attributes:
      label: Technology
      options:
        - JavaScript
        - Java
        - ASP.NET
        - PHP
        - Python
        - Go
        - CSS
        - Flutter
        - AI
        - Others
      description: Choose the technology of the project
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add a description for your project
      placeholder: ex. A react popup component
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
