name: New Youtube Channel
description: Fill this form to add your Youtube channel to the website.
title: "[New][Channel]: "
labels: ["new", "yt-channel"]

body:
  - type: markdown
    attributes:
      value: |
        Tell us about your channel.

  - type: input
    id: author
    attributes:
      label: Author fullname
      placeholder: ex. John Doe
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Author contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    id: contact-handler
    attributes:
      label: Author handler
      placeholder: https://github.com/user
    validations:
      required: false

  - type: input
    id: channel
    attributes:
      label: Channel title
      description: Add a title for your channel
      placeholder: ex. Geeksblabla
    validations:
      required: false

  - type: input
    id: channel-url
    attributes:
      label: Channel URL
      description: Add a url for your channel
      placeholder: ex. https://www.youtube.com/c/GeeksBlaBla01
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add a description for your channel
      placeholder: ex. My super channel
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
