name: New community
description: Fill this form to add your community to the website.
title: "[New][Community]: "
labels: ["new", "community"]

body:
  - type: markdown
    attributes:
      value: |
        Tell us about your community.

  - type: input
    id: author
    attributes:
      label: Author fullname
      placeholder: ex. John Doe
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Author contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    id: contact-handler
    attributes:
      label: Author handler
      placeholder: https://github.com/user
    validations:
      required: false

  - type: input
    id: community
    attributes:
      label: Community name
      description: Add a name for your community
      placeholder: ex. Dev C Morocco
    validations:
      required: false

  - type: input
    id: project-url
    attributes:
      label: Community URL
      description: Add a url for your community (page or website)
      placeholder: ex. https://discord.com/community/12345
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add a description for your community
      placeholder: ex. My community is about...
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
