# ✍️ Description:
# This action is to add missed article metadata for fetched articles.
# Should be run on a schedule, e.g. every day at 1am and update the metadata for 20 repos at a time
name: Article Metadata Update

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update-articles-metadata:
    name: Update Articles metadata
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📦 Setupbun + install deps
        uses: ./.github/actions/setup-bun-and-install

      - name: 🏃‍♂️ Update Articles metadata
        run: bun run update-articles-metadata
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL }}
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          XATA_BRANCH: ${{ secrets.XATA_BRANCH }}
          XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
          G_API_TOKEN: ${{ secrets.G_API_TOKEN }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
